apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-logging
  namespace: monitoring
  labels:
    k8s-app: elasticsearch-logging
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Elasticsearch"
spec:
  ports:
  - port: 9200
    protocol: TCP
    targetPort: 9200

---

kind: Endpoints
apiVersion: v1
metadata:
  name: elasticsearch-logging
  namespace: monitoring
subsets:
  - addresses:
      - ip: 1.2.3.4 # This will be replaced during deploy
    ports:
      - port: 9200