apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: wp-autoscaler
    namespace: wp
spec:
    scaleTargetRef:
        apiVersion: extensions/v1beta1
        kind: Deployment
        name: wp-wordpress
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 50
